version: "3.9"

services:
  backend:
    build:
      context: ./API
    container_name: virtual-eyes-backend
    ports:
      - "8000:8000"
    environment:
      - CAMERA_URL=http://10.56.90.145/capture
    networks:
      - virtualeyes_net
    restart: always

  frontend:
    build:
      context: ./Frontend
    container_name: virtual-eyes-frontend
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - BACKEND_URL=http://backend:8000   # ðŸ‘ˆ Lo usas desde Expo
    depends_on:
      - backend
    networks:
      - virtualeyes_net
    restart: always

networks:
  virtualeyes_net:
    driver: bridge
